### ISSUE TITLE
Plans for library function additions

### ISSUE THREAD

**Issue by sander48k** [PlayerData/react-native-mcu-manager#14]
Are there any plans to expose other functions (like e.g. FileSystemManager, device reset, etc.) of the iOS and Android library through this react native wrapper?

**Comment by ball-hayden** [comment]
Apologies @sander48k - I missed this.

We've no plans to expose other functions, but I'll happily review a PR.

**Comment by sander48k** [comment]
No problem @ball-hayden, thanks for your response. In our App we need to be able to reset a device and in the future we might need more functions. I have added the reset function for which I will create a PR soon.

**Comment by ball-hayden** [comment]
Hi @sander48k

Just a heads up - we're planning to do some significant work on this repo in the coming weeks.

If you're planning on submitting a PR, it might be worthwhile doing it sooner rather than later so it doesn't become outdated 🙂

**Comment by ball-hayden** [comment]
Closing this as I haven't heard anything back from @sander48k

**Comment by varunkudalkar** [comment]
@ball-hayden Did you get a chance to add more functions? I am in search of shell execution.
@sander48k Reply if you have something related to this.

**Comment by sander48k** [comment]
Hi, sorry for the late response @ball-hayden. Unfortunately I have very little time to work on this. I did not add any extra functions but I managed to add some improvements to the update process in this [feature branch](https://github.com/playpicoo/react-native-mcu-manager/tree/feature/additional_upgrade_options).

**Comment by ball-hayden** [comment]
@varunkudalkar I'm afraid we've no plans to expose other functions, but I'll happily review a PR.
