### ISSUE TITLE
Enable logging from Android Nordic library

### ISSUE THREAD

**Issue by sander48k** [PlayerData/react-native-mcu-manager#155]
Does anyone know how to enable logging from the Android Nordic library? The library uses the slf4j logging library but it is unclear how to get log messages directed to the Android logger.

**Comment by ball-hayden** [comment]
Fairly sure we've had logs through to `logcat` / the log viewer in Android Studio without any further changes, but I may be making that up.

You're probably better asking upstream at https://github.com/NordicSemiconductor/Android-nRF-Connect-Device-Manager/issues
