### ISSUE TITLE
"uploadProgress" event not working

### ISSUE THREAD

**Issue by benjamru** [PlayerData/react-native-mcu-manager#202]
These are the events specified in ReactNativeMcuManagerModule.kt
![image](https://github.com/PlayerData/react-native-mcu-manager/assets/158480051/89149204-14b3-4d01-b8eb-82ee80848002)

but in Upgrade.ts the event is named different
![image](https://github.com/PlayerData/react-native-mcu-manager/assets/158480051/c0c14056-ef0d-4bf4-aaa8-fa7e9ec38b07)

I believe the eventType in Ugrade.ts shold be "uploadProgressChanged" instead of "uploadProgress"

**Comment by ball-hayden** [comment]
@benjamru you're right.

`uploadProgress` is used consistently in the types, README, and Swift, so we're probably better changing the Kotlin to match.

Would you be able to open a PR to switch `ReactNativeMcuManagerModule.kt` to use `uploadProgress`?
