### ISSUE TITLE
The image does not have a valid mcu header

### ISSUE THREAD

**Issue by DevBySeb** [PlayerData/react-native-mcu-manager#297]
I keep getting the following error: "The image does not have a valid mcu header", do you know what the issue might be?

The .zip file contains a .bin-file, and is generated with Nordics Semiconductor nRF Connect.

**Comment by DevBySeb** [comment]
Worked fine - thanks for that mate!

**Comment by kumar-68150** [comment]
@DevBySeb  i upload .bin but same error on ios?
