### ISSUE TITLE
How to use this in react native cli?

### ISSUE THREAD

**Issue by kumar-68150** [PlayerData/react-native-mcu-manager#355]
How to use this in react native cli?

**Comment by ball-hayden** [comment]
It is not possible to use this from the react native CLI - you will need to use this within your React Native App.

**Comment by kumar-68150** [comment]
@ball-hayden you mean expo users only can use this ? if yes pls suggest  any library for cli app

**Comment by kumar-68150** [comment]
@ball-hayden is this firmware software update package?

**Comment by ball-hayden** [comment]
Yes, this package can be used to update MCUs that are running MCUMgr for firmware updates.

We use it with [nRF Connect SDK](https://www.nordicsemi.com/Products/Development-software/nRF-Connect-SDK), so it's most heavily tested with that, but it may be possible to use with other devices which run MCUMgr/MCUBoot.

**Comment by kumar-68150** [comment]
@ball-hayden Ok and  I receive the error  [Error: Invalid Header Magic Number. Are You Trying to DFU an Image That Has Not Been Properly Signed?]  even i upload .bin file can u have a idea?

**Comment by ball-hayden** [comment]
Afrait not. Sorry.

**Comment by tamilmani12** [comment]
@kumar-68150 did you got any idea or any other package for react native cli

**Comment by kumar-68150** [comment]
@tamilmani12  i used react-native-ble-manager it's working for me
