### ISSUE TITLE
runUpgrade() not triggering any event

### ISSUE THREAD

**Issue by FrancescoCerio** [PlayerData/react-native-mcu-manager#38]
Hello,

I'm using the provided example code inside this repo in order to update a nRF52840 (Nordic Semiconductor) board. 
The setup is working fine but when i try to run the runUpgrade() method nothing happens and no event is triggered.

I'm currently trying to update the firmware using a .bin file.

I'm wondering if the file extension is not correct.
Is there any suggestion on the file type to use for the upgrade?

### Platform used

- Android
- v. 10

### Package.json

```    
    "@playerdata/react-native-mcu-manager": "^2.3.4",
    "@react-navigation/native": "^6.1.6",
    "@react-navigation/native-stack": "^6.9.12",
    "lodash": "^4.17.21",
    "react": "18.2.0",
    "react-native": "0.71.11",
    "react-native-ble-plx": "^2.0.3",
    "react-native-document-picker": "^9.0.1",
    "react-native-get-random-values": "^1.9.0",
    "react-native-safe-area-context": "^4.5.3",
    "react-native-screens": "^3.21.1"
```

**Comment by lorenzolaricchia** [comment]
I'm having the same issue with a `nRF5` device.
Maybe the `.bin` file extension causes this issue?

**Comment by ball-hayden** [comment]
The file extension shouldn't be a problem - it's `app_update.bin` files that we use.

I'd suggest looking for logs on the MCU?
Do you see your central connect? If you turn up the MCUMgr log level, what do you see?

**Comment by FrancescoCerio** [comment]
when I try to run runUpgrade() I get this from the logs
```
Connected
I: Swap type: none
I: Swap type: none
Disconnected (reason 19)
```

**Comment by ball-hayden** [comment]
@FrancescoCerio did you discover what the issue was?
Would you mind sharing in case anyone else comes up with the same problem (like @lorenzolaricchia)?
