### ISSUE TITLE
EXC_BREAKPOINT, thread problem

### ISSUE THREAD

**Issue by alltodigital** [PlayerData/react-native-mcu-manager#56]
I'm getting an error on line 75 of FirmwareUpgradeManager. It hits a breakpoint i can't seem to get past it, apparently on library's internal use of GCD.

This is the crashlytics report:
crash_info_entry_0	BUG IN CLIENT OF LIBDISPATCH: Assertion failed: Block was expected to execute on queue [com.apple.main-thread (0x1fd461080)]

```
Crashed: com.facebook.react.McuManagerQueue
0  libdispatch.dylib              0x62c0 _dispatch_assert_queue_fail + 120
1  libdispatch.dylib              0x6248 _dispatch_assert_queue_fail + 194
2  libswiftDispatch.dylib         0x1218 _dispatchPreconditionTest(_:) + 48
3  lello                          0x74cbf4 FirmwareUpgradeManager.start(images:using:) + 95 (FirmwareUpgradeManager.swift:95)
4  lello                          0x74c528 FirmwareUpgradeManager.start(data:using:) + 67 (FirmwareUpgradeManager.swift:67)
5  lello                          0x7bdca8 DeviceUpgrade.startUpgrade(resolver:rejecter:) + 67 (DeviceUpgrade.swift:67)
6  lello                          0x7bf1dc RNMcuManager.runUpgrade(_:resolver:rejecter:) + 58 (McuManager.swift:58)
7  lello                          0x7bf308 @objc RNMcuManager.runUpgrade(_:resolver:rejecter:) + 608312 (<compiler-generated>:608312)
8  CoreFoundation                 0x72c04 __invoking___ + 148
9  CoreFoundation                 0x20cb4 -[NSInvocation invoke] + 428
10 CoreFoundation                 0x206cc -[NSInvocation invokeWithTarget:] + 64
11 lello                          0x6890d4 -[RCTModuleMethod invokeWithBridge:module:arguments:] + 587 (RCTModuleMethod.mm:587)
12 lello                          0x68b124 facebook::react::invokeInner(RCTBridge*, RCTModuleData*, unsigned int, folly::dynamic const&, int, (anonymous namespace)::SchedulingContext) + 196 (RCTNativeModule.mm:196)
13 lello                          0x68ad74 invocation function for block in facebook::react::RCTNativeModule::invoke(unsigned int, folly::dynamic&&, int) + 419 (Optional.h:419)
14 libdispatch.dylib              0x2320 _dispatch_call_block_and_release + 32
15 libdispatch.dylib              0x3eac _dispatch_client_callout + 20
16 libdispatch.dylib              0xb534 _dispatch_lane_serial_drain + 668
17 libdispatch.dylib              0xc0a4 _dispatch_lane_invoke + 384
18 libdispatch.dylib              0x16cdc _dispatch_workloop_worker_thread + 648
19 libsystem_pthread.dylib        0xddc _pthread_wqthread + 288
20 libsystem_pthread.dylib        0xb7c start_wqthread + 8
```

**Comment by alltodigital** [comment]
Can confirm this was the error. I edited the following on FirmwareUpgradeManager.swift and the firmware updated normaly:

`    public func start(images: [ImageManager.Image], using configuration: FirmwareUpgradeConfiguration = FirmwareUpgradeConfiguration()) throws {
        DispatchQueue.main.async {
            objc_sync_enter(self)
            defer {
                objc_sync_exit(self)
            }
            
            guard self.state == .none else {
                self.log(msg: "Firmware upgrade is already in progress", atLevel: .warning)
                return
            }
            
            do {
                self.images = try images.map { try FirmwareUpgradeImage($0) }
            } catch {
                // You might want to add some error handling here.
                // Maybe log the error or propagate it upwards.
                return
            }
            
            self.configuration = configuration
            
            // Grab a strong reference to something holding a strong reference to self.
            self.cyclicReferenceHolder = { return self }
            
            self.log(msg: "Upgrade started with \(images.count) images using '\(self.mode)' mode",
                    atLevel: .application)
            if #available(iOS 10.0, watchOS 3.0, *) {
                dispatchPrecondition(condition: .onQueue(.main))
            } else {
                assert(Thread.isMainThread)
            }
            self.delegate?.upgradeDidStart(controller: self)
            
            self.requestMcuMgrParameters()
        }
    }`

**Comment by ball-hayden** [comment]
Thanks @alltodigital - would you be able to submit a PR with your fix, please?

**Comment by Donald47** [comment]
This is hopefully resolved as of https://github.com/PlayerData/react-native-mcu-manager/releases/tag/v2.5.2
