### ISSUE TITLE
Firmware update on IOS not working

### ISSUE THREAD

**Issue by Sanjaya94** [PlayerData/react-native-mcu-manager#79]
I'm getting 'Error: Remote error: Bad State (1)' when trying firmware upgrade on IOS.Any idea?

**Comment by ball-hayden** [comment]
That sounds a lot like a fault on the MCU side - I would check the MCU logs.

When we've seen this, rebooting the MCU generally fixes the problem.

**Comment by ball-hayden** [comment]
@Sanjaya94 I'm closing this as I haven't heard any more from you, but please feel free to re-open if you've got MCU logs to help debug.
